### ISSUE TITLE
convertAll default List issue

### ISSUE THREAD

**Issue by GilHongHee** [MrDebugger/bs2json#2]
Hi, I'm using the bs2json library that you made it. 
I don't know if it's intended, but I think [convertAll] function has an issue cause of default variable in function.
When I call [convertAll] from the second or more times, return results are being added to the previous list. Below is some exaple.

`result = converter.convertAll([1,2,3])`
`result = converter.convertAll([4,5,6])`
`print(result)`

> [1, 2, 3, 4, 5, 6]

If you are not intended it, change the List initialization code to the below. 

`def convertAll(self, elements, List=None):`
` if List is None: List=[]`

Best regards.

**Comment by MrDebugger** [comment]
Thank You, i will edit this

**Comment by MrDebugger** [comment]
@GilHongHee do a pull request and i will merge it

**Comment by MrDebugger** [comment]
**fixed**

**Comment by GilHongHee** [comment]
Hi, Maybe you miss spell in added code.
`List = l`

**Comment by MrDebugger** [comment]
LOL, Yes Thank You

**Comment by MrDebugger** [comment]
Can you confirm the fix now,
Thank You for this to point out.
