### ISSUE TITLE
be able to update the label attributes and text

### ISSUE THREAD

**Issue by cyril36** [MrDebugger/bs2json#5]
It would be nice to be able to update the label attributes and text 
if i am converting a xml file with attributes tag defined, i wont get the right result :
my xml file : 

```
<channel test='test'>
    <title>Crime Junkie</title>
    <link>https://crixxxx.com/</link>
    <attributes>en</attributes>

```
Current result of convert(xml) is losing the channel attribute "test:"test":
```
channel:{
  "attributes": {
    "attributes": {},
    "text": "en"
  },
  "link": {
    "attributes": {},
    "text": "httxxx.com/"
  },
  "title": {
    "attributes": {},
    "text": "Crime Junkie"
  }
  "text":""
}
```

**Would it be possible to add a parameter to specify the attributes and text label ?**

such as : 
By default : 
```
In bs2json.py - line 4 : 
convert(self,element,json={},customLabel={"attributes" : "attributes", "text" : "text"})

```
And in my script i would do :
```
myCustomLabel = {"attributes" : "xxxx", "text" : "yyyy"}
convert(my_bs_elmt, customLabel=myCustomLabel)

```
The result would be the following and we would not loose any information: 
```
channel:{
  "xxxx" : {"test":"test"}
  "attributes": {
    "xxxx": {},
    "yyyy": "en"
  },
  "link": {
    "xxxx": {},
    "yyyy": "httxxx.com/"
  },
  "title": {
    "xxxx": {},
    "yyyy": "Crime Junkie"
  }
  "yyyy":""
}
```

Thank you

**Comment by MrDebugger** [comment]
It is possible and would love to add those features in next update.

**Comment by MrDebugger** [comment]
@cyril36 Sorry for late update, the feature has been added to the code and soon will be published on the pypi
