### ISSUE TITLE
TypeError bs4.element not NoneType

### ISSUE THREAD

**Issue by ktavabi** [MrDebugger/bs2json#6]
From your own example...

```
from bs4 import BeautifulSoup
from requests import get
from bs2json import bs2json
html = get('https://ijazurrahim.com').text
soup = BeautifulSoup(html,'lxml')
converter = bs2json()
tag = soup.find('ul')
json = converter.convert(tag)
print(json)
```

> TypeError                                 Traceback (most recent call last)
> ~/Documents/Projects/Apeshit/convert_xml_csv.py in <module>
>       9 
>      10 tag = soup.find('ul')
> ---> 11 json = converter.convert(tag)
>      12 print(json)
> 
> ~python3.9/site-packages/bs2json/bs2json.py in convert(self, element, json)
>       9                         return json
>      10                 else:
> ---> 11                         raise TypeError(f"convert(x,y) `x` argument must be a {Element.__name__} not {type(element).__name__}")
>      12 
>      13         def convertAll(self,elements,L=None):
> 
> TypeError: convert(x,y) `x` argument must be a bs4.element not NoneType

**Comment by MrDebugger** [comment]
@ktavabi site was updated and the `ul` tag was removed which is resulting this error.
